### ISSUE TITLE
Export mockup(s)

### ISSUE THREAD

**Issue by pglevy** [Bixal/dpc-design-challenge#7]
It's unclear to me from the challenge details what "Submit a screenshot of your mockup as an entry to the challenge" means. I'm not sure if they just want like a "cover page" or if we should include multiple "key screens." I'm assuming they don't want exports of each screen.

So let's figure out what screens it makes sense to pull out as "screenshots." What would we include if we uploading this to the App Store?

**Comment by demi-johnson** [comment]
Maybe images of the dashboards? And a requirement page?
